version: '3.8'
services:
  db_ecommerce:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ecommerce
      - POSTGRES_DB=ecommerce
      - POSTGRES_PASSWORD=ecommerce